apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod-declarativo
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    # ports:
    #   - containerPort: <Port>
