apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: portal-noticia
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
    envFrom:
      - configMapRef:
          name: portal-configmap
