apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-container
        name: primeiro-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: jenkins
    image: jenkins/jenkins:lts-jdk11
    volumeMounts:
      - mountPath: /volume-dentro-container
        name: primeiro-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/primeiro-volume
        type: DirectoryOrCreate

